---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-json
        exclude: devcontainer.json
      - id: check-yaml
        exclude: keda-2.10.0.yaml
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key

  - repo: https://github.com/bridgecrewio/checkov.git
    rev: '2.2.234'
    hooks:
      - id: checkov
        verbose: false
        args: []

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    # Get the latest from:
    # https://github.com/antonbabenko/pre-commit-terraform/releases
    rev: v1.76.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      # - id: terraform_tfsec
      - id: terraform_tflint

  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0"
    hooks:
      - id: terraform-docs-go
        args: ["markdown", "table", "--output-file", "README.md", "./"]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8

  -   repo: https://github.com/PyCQA/isort
      rev: 5.12.0
      hooks:
        -   id: isort

  - repo: https://github.com/stackrox/kube-linter
    rev: v0.6.3
    hooks:
      - id: kube-linter
