---


apiVersion: batch/v1
kind: Job
metadata:
  name: azure-pipelines-setup
  namespace: "{{ .Values.namespace }}"
  annotations:
    bridgecrew.io/skip1: CKV_K8S_22=Use read-only filesystem for containers where possible
    # TODO: check if this can be implemented
    bridgecrew.io/skip2: CKV_K8S_23=Minimize the admission of root containers
    # does not actually actively run container images
    bridgecrew.io/skip3: CKV_K8S_43="Image should use digest"
    # TODO: check if this can be implemented
    bridgecrew.io/skip4: CKV_K8S_35="Prefer using secrets as files over secrets as environment variables"
    # TODO: check if this can be implemented
    bridgecrew.io/skip5: CKV_K8S_40="Containers should run as a high UID to avoid host conflict"
spec:
  activeDeadlineSeconds: 300
  backoffLimit: 0
  ttlSecondsAfterFinished: 600
  template:
    spec:
      automountServiceAccountToken: false
      restartPolicy: Never
      activeDeadlineSeconds: 240
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: azure-pipelines-agent
          image: "{{ .Values.container.image}}"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop:
                - NET_RAW
                - ALL
          resources:
            limits:
              cpu: 0.2
              memory: 50Mi
            requests:
              cpu: 0.2
              memory: 50Mi
          imagePullPolicy: Always
          env:
            - name: AZP_AGENT_NAME
              value: placeholder-agent
            - name: AZP_POOL
              value: "{{ .Values.pool.name}}"
          envFrom:
            - secretRef:
                name: pipeline-auth
