apiVersion: batch/v1
kind: Job
metadata:
  name: azure-pipelines-setup
  namespace: ${namespace}
spec:
  activeDeadlineSeconds: 300
  backoffLimit: 0
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      activeDeadlineSeconds: 240
      containers:
        - name: azure-pipelines-agent
          image: ${image}
          imagePullPolicy: Always
          env:
            - name: AZP_AGENT_NAME
              value: placeholder-agent
            - name: AZP_POOL
              value: ${pool_name}
          envFrom:
            - secretRef:
                name: pipeline-auth
