apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: azure-pipelines-scaledjob
  namespace: ${namespace}
spec:
  # https://keda.sh/docs/2.5/scalers/azure-pipelines/
  triggers:
    - type: azure-pipelines
      metadata:
        poolID: "${pool_id}"
        organizationURLFromEnv: "AZP_URL"
        personalAccessTokenFromEnv: "AZP_TOKEN"
  jobTargetRef:
    activeDeadlineSeconds: 14400  # 4h
    # backOffLimit: 0  # works with newer KEDA versions
    template:
      spec:
        restartPolicy: Never
        containers:
          - name: azure-pipelines-agent
            # image is created like described in https://keda.sh/docs/2.9/scalers/azure-pipelines/#configuring-the-agent-container
            # don't forget the mentioned script change as well as mine
            image: ${image}
            imagePullPolicy: Always
            env:
            - name: AZP_POOL
              value: "${pool_name}"
            envFrom:
              - secretRef:
                  name: pipeline-auth
  pollingInterval: 10
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  maxReplicaCount: 30
  rollout:
    strategy: gradual  # if ScaledJob changes, don't terminate currently running jobs
