---

name: test

# yamllint disable rule:truthy
on:
  workflow_dispatch:

jobs:
  cluster_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
        with:
          node_image: kindest/node:v1.25.8@sha256:00d3f5314cc35327706776e95b2f8e504198ce59ac545d0200a89e69fce10b7f
          cluster_name: kind

      - name: Run a multi-line script
        run: |
          kubectl version
          kubectl config get-contexts
          kubectl get nodes
