---

name: test-report

# yamllint disable rule:truthy
on:
  workflow_run:
    workflows: ['tests']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: tftest tests
          path: 'tests/*.xml'
          reporter: jest-junit
